In [5]:
import pandas as pd

df_rendement = pd.read_csv("VFAOSTAT_data_fr_8-11-2026 (3).csv")
df_pluie = pd.read_csv("VPOWER_Point_Monthly_20000101_20201231_014d70N_017d04W_LST.csv", skiprows=9)

In [6]:
df_rendement.shape
df_rendement.head(10)

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,142,Arachides non décortiquées,2000,2000,kg/ha,969.1,A,Valeur officielle,NaN
1,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,142,Arachides non décortiquées,2020,2020,kg/ha,1467.2,A,Valeur officielle,NaN
2,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,112,Maïs,2000,2000,kg/ha,1111.4,A,Valeur officielle,NaN
3,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,112,Maïs,2020,2020,kg/ha,2654.9,A,Valeur officielle,NaN
4,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,118,Mils,2000,2000,kg/ha,712.7,A,Valeur officielle,NaN
5,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,118,Mils,2020,2020,kg/ha,1119.0,A,Valeur officielle,NaN
6,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,113,Riz,2000,2000,kg/ha,2345.4,A,Valeur officielle,NaN
7,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,113,Riz,2020,2020,kg/ha,3343.2,A,Valeur officielle,NaN
8,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,114,Sorgho,2000,2000,kg/ha,869.1,A,Valeur officielle,NaN
9,QCL,Cultures et produits animaux,686,Sénégal,5412,Rendement,114,Sorgho,2020,2020,kg/ha,1356.8,A,Valeur officielle,NaN

In [7]:
df_pluie.shape
df_pluie.head(10)

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,PRECTOTCORR_SUM,2000,0.94,0.85,0.00,0.16,0.34,5.28,69.39,119.89,97.82,87.97,0.08,0.24,382.96
1,PRECTOTCORR_SUM,2001,0.01,0.43,0.01,0.08,0.19,10.44,91.73,120.88,81.42,10.05,4.36,0.62,320.22
2,PRECTOTCORR_SUM,2002,20.64,0.46,0.83,0.07,0.20,10.16,8.75,101.96,101.12,33.37,0.50,3.27,281.33
3,PRECTOTCORR_SUM,2003,0.29,0.43,0.09,0.63,0.19,20.26,57.57,139.07,150.07,54.05,0.11,0.44,423.20
4,PRECTOTCORR_SUM,2004,2.18,0.05,0.23,0.49,0.70,16.81,65.47,161.97,131.07,18.30,4.22,0.38,401.87
5,PRECTOTCORR_SUM,2005,0.44,8.08,0.24,1.13,1.51,30.82,147.28,220.36,157.46,72.93,0.49,0.30,641.04
6,PRECTOTCORR_SUM,2006,21.31,2.86,0.30,0.04,1.94,21.01,63.80,212.21,191.29,60.72,0.42,0.86,576.76
7,PRECTOTCORR_SUM,2007,0.12,0.05,0.68,0.51,1.30,7.47,93.14,199.64,189.57,18.43,0.30,0.27,511.48
8,PRECTOTCORR_SUM,2008,0.69,9.54,0.03,0.07,1.42,22.73,214.29,309.67,206.82,43.81,0.11,0.09,809.27
9,PRECTOTCORR_SUM,2009,0.25,0.96,0.11,0.07,0.24,23.01,155.01,395.77,222.91,27.95,4.66,1.75,832.69

In [8]:
df_pluie_long = df_pluie.melt(
    id_vars=['YEAR'],           # la colonne qu'on garde telle quelle
    value_vars=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],  # les colonnes à "empiler"
    var_name='mois',            # nom de la nouvelle colonne qui contiendra JAN, FEB, etc.
    value_name='precipitation'  # nom de la nouvelle colonne qui contiendra les valeurs
)

In [9]:
df_pluie_long.shape
df_pluie_long.head(15)

    YEAR mois  precipitation
0   2000  JAN           0.94
1   2001  JAN           0.01
2   2002  JAN          20.64
3   2003  JAN           0.29
4   2004  JAN           2.18
5   2005  JAN           0.44
6   2006  JAN          21.31
7   2007  JAN           0.12
8   2008  JAN           0.69
9   2009  JAN           0.25
10  2010  JAN           0.24
11  2011  JAN           0.38
12  2012  JAN           0.18
13  2013  JAN           0.83
14  2014  JAN           1.80

In [10]:
mois_vers_numero = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

df_pluie_long['mois_num'] = df_pluie_long['mois'].map(mois_vers_numero)

In [11]:
df_pluie_long = df_pluie_long.sort_values(['YEAR', 'mois_num']).reset_index(drop=True)

In [12]:
df_pluie_long.head(15)

    YEAR mois  precipitation  mois_num
0   2000  JAN           0.94         1
1   2000  FEB           0.85         2
2   2000  MAR           0.00         3
3   2000  APR           0.16         4
4   2000  MAY           0.34         5
5   2000  JUN           5.28         6
6   2000  JUL          69.39         7
7   2000  AUG         119.89         8
8   2000  SEP          97.82         9
9   2000  OCT          87.97        10
10  2000  NOV           0.08        11
11  2000  DEC           0.24        12
12  2001  JAN           0.01         1
13  2001  FEB           0.43         2
14  2001  MAR           0.01         3